### ISSUE TITLE
Required attributes seem to = all attributes

### ISSUE THREAD

**Issue by dmvt** [emque/emque-producing#33]
```
2.2.2 :002 > SlackMessage.new(:message => "This is only a test", :channel => "test-ground").publish
Emque::Producing::Message::InvalidMessageError: Required attributes [:icon] are missing.
	from /Users/danmatthews/.rvm/gems/ruby-2.2.2/gems/emque-producing-1.0.2/lib/emque/producing/message/message.rb:124:in `publish'
	from (irb):2
	from /Users/danmatthews/.rvm/gems/ruby-2.2.2/bundler/gems/rails-d43b4163dc1f/railties/lib/rails/commands/console.rb:47:in `start'
	from /Users/danmatthews/.rvm/gems/ruby-2.2.2/bundler/gems/rails-d43b4163dc1f/railties/lib/rails/commands/console.rb:8:in `start'
	from /Users/danmatthews/.rvm/gems/ruby-2.2.2/bundler/gems/rails-d43b4163dc1f/railties/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

```ruby
class SlackMessage
  include Emque::Producing::Message

  topic "messages"
  message_type "message.slack"

  attribute :message, String, :required => true
  attribute :channel, String, :required => true
  attribute :icon, String
end
```

**Comment by dmvt** [comment]
Ahh... I see... `:required => true` is the default. We should perhaps re-evaluate this... seems a bit counter-intuitive

**Comment by ryanwi** [comment]
Seems that way, I started looking it at and created some test for it (https://github.com/emque/emque-producing/pull/34).

I read it as this being a Virtus issue, do you read this as required is the default? https://github.com/solnic/virtus/blob/9089f714c21ce295130f85de4fb27430d0870801/lib/virtus/attribute.rb#L26

**Comment by dmvt** [comment]
Yeah... guess we should stick with it. Closing this one...
